# Generated by Django 2.2.3 on 2019-07-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instName', models.CharField(max_length=50)),
                ('batchName', models.CharField(max_length=50)),
            ],
        ),
    ]
