# Generated by Django 2.2.3 on 2019-07-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0004_auto_20190724_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instName', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
    ]
