# Generated by Django 2.2.3 on 2019-07-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0006_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
