# Generated by Django 2.2.3 on 2019-07-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0010_auto_20190727_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quizName',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
