# Generated by Django 2.2.3 on 2019-07-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0011_auto_20190727_0532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
