# Generated by Django 2.2.3 on 2019-07-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0013_quiz'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('instName', 'batchName')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('instName', 'batch', 'subject')},
        ),
    ]
