# Generated by Django 2.2.3 on 2019-07-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0015_quiz_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyQuiz',
            fields=[
                ('instName', models.CharField(max_length=50)),
                ('quizName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
            ],
        ),
    ]
