# Generated by Django 2.2.3 on 2019-07-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0016_readyquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyquiz',
            name='attempts',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readyquiz',
            name='time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
