# Generated by Django 2.2.3 on 2019-07-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0017_auto_20190730_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instName', models.CharField(max_length=50)),
                ('quizName', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('correctAnswer', models.CharField(max_length=50)),
                ('totalPoints', models.CharField(max_length=50)),
                ('quizDate', models.DateField(max_length=50)),
                ('quizTime', models.CharField(max_length=50)),
                ('stuEmail', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='readyquiz',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readyquiz',
            name='quizName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='readyquiz',
            unique_together={('instName', 'batch', 'subject', 'quizName')},
        ),
    ]
