# Generated by Django 2.2.3 on 2019-08-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0019_quizresult_totalques'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacherEmail',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
