# Generated by Django 2.2.4 on 2019-08-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0020_subject_teacheremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instName', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('teacherEmail', models.CharField(max_length=50)),
                ('folderName', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('instName', 'batch', 'subject', 'teacherEmail', 'folderName')},
            },
        ),
    ]
